### ISSUE TITLE
Wikipedi

### ISSUE THREAD

**Issue by juli64** [docker/compose#11455]
`Wikipedia.Wikimedia`[Bug]updates 
```[tasklist]
### Tasks
- [x] https://github.com/docker/compose/issues/11456
- [ ] https://github.com/docker/compose/issues/11414
- [ ] https://github.com/docker/compose/issues/4581
- [x] https://github.com/docker/compose/issues/11457
```
