### ISSUE TITLE
Epic: Improve performance by running operations in parallel

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1652]
Many of Compose's actions can be performed in parallel rather than in sequence. For larger apps, this would result in enormously reduced startup/redeploy times.

This is a meta-issue for keeping track of all of the stuff happening around that, in rough priority order.
- [x] `docker-compose (stop|kill|remove)`: https://github.com/docker/compose/issues/1651
- [x] `docker-compose scale`: https://github.com/docker/compose/issues/1653
- [x] `docker-compose up`: Creating, pulling, building and starting in `up` can be done in parallel: #1984
- [x] `docker-compose pull`: Multiple services can be pulled in parallel.
- [x] `docker-compose pull --parallel` is the default (deprecate flag).

(Replaces #1395)

**Comment by dnephin** [comment]
#931 is also related, doing pull and build in parallel (although I don't think build will benefit at all).

**Comment by gkze** [comment]
Bump -- this would be amazing since we are having to deal with more and more services in containers that don't depend on each other, so this would help speed up the process immensely

**Comment by aanand** [comment]
@gkze `stop`, `kill`, `rm` and `scale` now work in parallel - try it out in [Compose 1.4.0 RC2](https://github.com/docker/compose/releases/tag/1.4.0rc2).

**Comment by k2xl** [comment]
Cool. What about dc build?

**Comment by dnephin** [comment]
@k2xl because of this https://github.com/docker/docker/issues/9656 bug/limitation in docker doing build in parallel in compose would actually make things slower. Once that's fixed, it should be pretty easy to add.

**Comment by IlyaSkriblovsky** [comment]
Hi! What you would suggest if my app needs to write something to DB when stopping gracefully? Is it possible to acheive ordered stopping with Compose?

@aanand said in #1395:
> 3. Container stopping/killing should be completely order-independent - if it's all going down, it doesn't matter what order we do it in.
While this is true for almost any regular web app, but I can't agree with that for something more stateful. For example, when my server receives stop signal, it gracefully closes all active connections and saves log records on each disconnection to DB. I'm trying to dockerize my app with Compose and this seems to be an issue :(  Thanks for advice.

**Comment by willejs** [comment]
+1 looking forward to this feature.

**Comment by khalilj** [comment]
+1

**Comment by IlyaSkriblovsky** [comment]
Starting phase of `up` made parallel in #2679 (and also `start` and `stop`)

**Comment by morlajb** [comment]
+1

**Comment by niieani** [comment]
How about `build`? When building on a docker-swarm, many nodes can build the images independently.

**Comment by chesleybrown** [comment]
No update on this issue in quite awhile. Is there still interest in:

> docker-compose pull: Multiple services can be pulled in parallel.

I know for us it would be a huge improvement as we have many images that have to be pulled. At this point I've even debated scripting each service to be pulled individually so we could do it in parallel. Thoughts?

**Comment by fesor** [comment]
Until #4428 is not merged this simple bash script could be used:

```
for service in $(docker-compose config --services); do
    docker-compose pull $service &
done
wait
```

**Comment by shin-** [comment]
With #4428 merged in, it is now possible to do `docker-compose pull --parallel`. If feedback on the feature is good we'll be able to make it the default behavior in the future.

**Comment by schmod** [comment]
Is `push` on the list somewhere too?

**Comment by batytskyy** [comment]
+1

**Comment by jordanarseno** [comment]
+1 for `build` parallel.

**Comment by shin-** [comment]
Parallel build is still blocked by https://github.com/moby/moby/issues/9656
