### ISSUE TITLE
Epic: Define an application once in a way that can be used in dev, test and prod

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1784]
It should be possible to define a single file that can abstractly describe the high-level structure of application. This file should be able to be used across development, test and production with no modification, but may need additional configuration files or environment variables to describe the variances between environments.

**Related things:**

 - [x] [`extends` in Compose files](https://docs.docker.com/compose/extends/). This was a good start, but is still pretty clunky for achieving the above.
 - [x] [Interpolate environment variables in Compose files](https://github.com/docker/compose/issues/1377)
 - [x] Research use cases and what users want to do
 - [x] [Extend an entire Compose file](https://github.com/docker/compose/issues/1987)
 - [x] Recommend patterns for achieving what users want to do (see also #1786)

(This list is not a complete list of what it will take to achieve this goal, and may change as we research what users want.)

**Research:**

- Here is a recommended setup for how to run a Django app in both dev and production with Compose, using two different Compose files: https://github.com/pydanny/cookiecutter-django/pull/284
- User feedback on extends and where it falls short for this use case: https://github.com/docker/compose/issues/1380
- [Example production Compose files](https://github.com/search?utf8=%E2%9C%93&q=in%3Apath+docker-compose-prod.yml+extension%3Ayml&type=Code&ref=searchresults)

**Comment by aanand** [comment]
#1380 provides some user feedback on `extends` and where it falls short for this use case.

**Comment by dnephin** [comment]
I think https://github.com/dnephin/compose-addons#dcao-merge addresses some of this. It provides a convenient way to vary a configuration but keep a similar base.

**Comment by dnephin** [comment]
This is now documented in `extends.md`
