### ISSUE TITLE
Epic: Support Docker's new networking model

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1803]
Docker has introduced a new top-level concept of a "network", accompanied by new CLI and API functionality. Compose should support this – both out of the box, and allowing the user to manually configure complex topologies.

- [x] Experimental support for networks - https://github.com/docker/compose/pull/2191
- [x] Specify networks in the Compose file - https://github.com/docker/compose/issues/2478
- [x] Move network support out of experimental status and make it the default (or only) means of inter-service communication
 - [x] Use service name and short name alises #2312
 - [x] Support setting the default network name #2470

**Comment by aanand** [comment]
Updated with TODO.

**Comment by dnephin** [comment]
I think "Support setting the default network name #2470" is supported by creating `default` and making it use `external`, but I'm not sure if we have a test for it to confirm.

**Comment by aanand** [comment]
@dnephin Done one in https://github.com/docker/compose/pull/2696
