### ISSUE TITLE
Stable Compose / Swarm integration

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1910]
It should be possible to point Compose at Swarm and have it run any Compose app that runs on a single Engine.

This is also being tracked on Swarm's side here: https://github.com/docker/swarm/issues/1156
### Sub-issues
- [ ] Run the Compose test suite against a Swarm cluster
- [x] https://github.com/docker/swarm/issues/1244
- [x] https://github.com/docker/compose/issues/1913
- [ ] https://github.com/docker/compose/issues/1528
- [ ] #2131
- [x] https://github.com/docker/swarm/issues/1257
- [ ] #2169
- [x] https://github.com/docker/swarm/issues/1293
- [x] https://github.com/docker/swarm/issues/1316

**Comment by dnephin** [comment]
Related issues: #1913, #1528

I think step 1 here might be "run the compose test suite against a swarm cluster".

**Comment by bfirsh** [comment]
:+1: thanks

**Comment by dnephin** [comment]
#1090 is related, but might already be fixed

**Comment by dnephin** [comment]
This is blocked on https://github.com/docker/swarm/issues/1244

**Comment by dnephin** [comment]
Possible #2374

**Comment by dnephin** [comment]
I've created a new swarm label: https://github.com/docker/compose/labels/swarm to track related issues, instead of having to come update the checklist in this issue.

**Comment by bfirsh** [comment]
Wow what a throwback. Hi everyone. 😂
