### ISSUE TITLE
Support Windows Engine

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2641]
Issues with Compose pointing at an Engine running on Windows (i.e. Windows containers) are collected under the [group/windows-server](https://github.com/docker/compose/labels/group%2Fwindows-server) label. The Compose client could be running on either Linux or Windows.

This is a list of things we want to deliver for Compose 1.8 related to Windows Engine.
- [x] Networking doesn't work with Windows containers due to disconnecting containers from networks #3252 
- [x] Windows volume paths don't work #2487 (we can look at how docker-cli does it)
- [x] Support npipe for docker host #3170 
## See also
- [Issues with Compose client running on Windows](https://github.com/docker/compose/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Agroup%2Fwindows-client+)

**Comment by git-jiby-me** [comment]
@dnephin the checklist shows that networking in windows due to disconnecting containers from networks not supported in windows as fixed. However when i try head of docker engine, swarm and compose, i still get the error that "windows doesn't support disconnecting containers from networks". Is this still something pending to be fixed ?

**Comment by dnephin** [comment]
It's still pending, I've unchecked the box.

**Comment by git-jiby-me** [comment]
@dnephin ah, roger that, thanks for the update :)

**Comment by shin-** [comment]
Removing milestone, see https://github.com/docker/compose/issues/3252#issuecomment-254341319

**Comment by abergs** [comment]
Any updates?
