### ISSUE TITLE
Epic: "compose run" should support every "docker run" option

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#363]
`fig run` should support every option of `docker run`, just referring to a service instead of an image.

```
Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

  -a, --attach=[]            Attach to stdin, stdout or stderr.
  -c, --cpu-shares=0         CPU shares (relative weight)
  --cidfile=""               Write the container ID to the file
  --cpuset=""                CPUs in which to allow execution (0-3, 0,1)
  -d, --detach=false         Detached mode: Run container in the background, print new container id
  --dns=[]                   Set custom dns servers
  --dns-search=[]            Set custom dns search domains
  -e, --env=[]               Set environment variables
  --entrypoint=""            Overwrite the default entrypoint of the image
  --env-file=[]              Read in a line delimited file of ENV variables
  --expose=[]                Expose a port from the container without publishing it to your host
  -h, --hostname=""          Container host name
  -i, --interactive=false    Keep stdin open even if not attached
  --link=[]                  Add link to another container (name:alias)
  --lxc-conf=[]              (lxc exec-driver only) Add custom lxc options --lxc-conf="lxc.cgroup.cpuset.cpus = 0,1"
  -m, --memory=""            Memory limit (format: <number><optional unit>, where unit = b, k, m or g)
  --name=""                  Assign a name to the container
  --net="bridge"             Set the Network mode for the container
                               'bridge': creates a new network stack for the container on the docker bridge
                               'none': no networking for this container
                               'container:<name|id>': reuses another container network stack
                               'host': use the host network stack inside the container.  Note: the host mode gives the container full access to local system services such as D-bus and is therefore considered insecure.
  -P, --publish-all=false    Publish all exposed ports to the host interfaces
  -p, --publish=[]           Publish a container's port to the host
                               format: ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort
                               (use 'docker port' to see the actual mapping)
  --privileged=false         Give extended privileges to this container
  --rm=false                 Automatically remove the container when it exits (incompatible with -d)
  --sig-proxy=true           Proxify received signals to the process (even in non-tty mode). SIGCHLD is not proxied.
  -t, --tty=false            Allocate a pseudo-tty
  -u, --user=""              Username or UID
  -v, --volume=[]            Bind mount a volume (e.g., from the host: -v /host:/container, from docker: -v /container)
  --volumes-from=[]          Mount volumes from the specified container(s)
  -w, --workdir=""           Working directory inside the container
```
## Todo (in rough priority order)
- [x] `-u` https://github.com/docker/compose/pull/971
- [x] `--entrypoint` https://github.com/docker/compose/pull/511
- [x] `-w` https://github.com/docker/compose/pull/332
- [x] `-p` https://github.com/docker/compose/issues/1709
- [x] `-v`
- [x] `--cpuset`
- [x] `--memory`
- [x] `--env-file`
- [x] `--net`
- [x] `--memory-swappiness` #2383
- [ ] `--volumes-from` #1769

**Comment by hadim** [comment]
+1

**Comment by WalterInSH** [comment]
+1

**Comment by fntlnz** [comment]
:+1:  Not having restart policy is blocking for me

**Comment by thaJeztah** [comment]
Restart policies have been implemented and will be part of the docker-compose 1.1 release (fig has been re-named to docker-compose in the next release)

Release candidates are available for download in the releases tab and the list of changes  can be found here; https://github.com/docker/fig/blob/master/CHANGES.md

**Comment by fntlnz** [comment]
Thank you @thaJeztah  I'll take a look at this.

**Comment by kikicarbonell** [comment]
:+1: I desperately need `--cpuset and --memory`

**Comment by bfirsh** [comment]
`user` being added here: https://github.com/docker/compose/pull/971

**Comment by bfirsh** [comment]
I've added some pull requests of options being added to the description in case anybody needs an example to help them add these.

**Comment by josephpage** [comment]
:+1:   I need `-v, --volume=[]` option

**Comment by tophsic** [comment]
:+1:

**Comment by KingScooty** [comment]
:+1: 

--net=host -e

**Comment by andrewwatson** [comment]
if it just supported --tlscacert --tlscert --tlskey and -H it would make it possible to use it conjuction with the output from docker machine config like so:

```
docker-compose $(docker-machine config) up -d
```

**Comment by aanm** [comment]
@andrewwatson
Have you tried:
```bash
$ eval $(docker-machine config) 
$ docker-compose up -d
```

**Comment by andrewwatson** [comment]
Yes, that works fine but if you're invoking compose from something like the remote-exec block of terraform it's not awesome having to eval things into the environment in the middle of what's already a giant embedded shell script...

**Comment by andrewwatson** [comment]
so what I'm working on would be to tack this on to TopLevelCommand...
```
      -H                        Daemon socket(s) to use or connect to
      --tlsverify               Use TLS and verify the remote
      --tlscacert               Trust certs signed only by this CA
      --tlscert                 Path to TLS certificate file
      --tlskey                  Path to TLS key file
```
straight out of the output from "docker help" and then grab those CLI options in command.py here https://github.com/docker/compose/blob/master/compose/cli/command.py#L50 and then pass them down to docker_client.py.  

Sound good?

**Comment by dnephin** [comment]
yup, that sounds right

**Comment by ekristen** [comment]
+1 for supporing -H and -tls options!

**Comment by bfirsh** [comment]
@ekristen I have created this to track that feature: https://github.com/docker/compose/issues/1716

**Comment by ekristen** [comment]
@bfirsh thanks

**Comment by brondsem** [comment]
`-w` #332 is actually not completed :(

**Comment by lbradstreet** [comment]
docker-compose does not support the new --shm-size option

**Comment by antony** [comment]
Another thing which is really important here is --rm=false which CircleCI needs to not print errors all over the place. You can't remove containers on CircleCI (for some reason relating to permissions I think) so therefore you can't use docker-compose to build containers satisfactorily.

**Comment by Nokel81** [comment]
Will this, by way of association, work with `docker-compse "name" up` so we could do `docker-compse "name" up --cpuset="0-3"`?

This currently is odd since in the docker-compose.yml it is possible to set which cpu to use.

**Comment by thaJeztah** [comment]
@Nokel81 `docker-compose up` is not the equivalent of `docker run`, because it starts the whole "stack" (all services). Adding `--cpuset="0-3"` would not make sense there, because it would then be applied to all services.

**Comment by Nokel81** [comment]
@thaJeztah Then how would I allow `cpuset: "3"` in the docker-compose.yml file? I get an error saying "ERROR: Requested CPUs are not available - requested 3, available: 0."

**Comment by allancaffee** [comment]
I'd love to be able to mount a `--volume` for a one-off command. It would facilitate being able to load DB data from a prod snapshot for instance.

**Comment by eddwardo** [comment]
Work on `-v` is being done here: https://github.com/docker/compose/pull/4042

**Comment by borntorock** [comment]
Hi, Any update on the `--init` option, recently introduced with Docker v1.13

**Comment by ajthemacboy** [comment]
`--cpuset` would be very useful!

**Comment by eddwardo** [comment]
`-v`is done here: https://github.com/docker/compose/pull/4566

**Comment by jasonben** [comment]
I want to use resource constraints without a swarm. How can I do that in my version: "3" docker-compose.yml?

https://docs.docker.com/compose/compose-file/#resources

```yaml
deploy:
  resources:
    limits:
      memory: "1G"
      cpus: "0.01"
```

WARNING: Some services ... use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration

**Comment by zimmertr** [comment]
@jasonben did you find an answer for this?

**Comment by thaJeztah** [comment]
@zimmertr use the `--compatibility` flag; see https://github.com/docker/compose/pull/5684

**Comment by eddwardo** [comment]
`-v` has a bug. Fix in https://github.com/docker/compose/pull/5370

**Comment by jimmyharris** [comment]
Can we setup signal proxying as a thing? It would be nice if signals received by `docker-compose run` would be proxied to the underlying command. Additionally getting the exit code form the underlying command would be good as well.
