### ISSUE TITLE
Epic: Use less disk space

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#53]
There are a bunch of things we could do:
- [x] `build -rm` by default
- [ ] `run -rm` by default when doing `fig run`
- [ ] maybe remove containers by default if they don't have volumes?
- [x] pull latest tag by default https://github.com/docker/fig/pull/716

**Comment by dnephin** [comment]
I created this tool for doing cleanup https://github.com/yelp/docker-custodian

I think removing  containers by default might be assuming too much about how compose is being used. Especially now that we have start-recreate which is able to start containers again.

@bfirsh  do you think there is still work to be done here on the compose side?

**Comment by shin-** [comment]
With `docker-compose down` and `docker system prune` now, I thin we're in a good place regarding managing disk space.
