### ISSUE TITLE
Rebrand (post-RC, pre-stable)

### ISSUE THREAD

**Issue by aanand** [docker/compose#861]
These are the steps to take before the stable release of Compose 1.1.0.

- [x] Rename the GitHub repo
- [x] Update install docs with new binary URL (#1021)
- [x] Update completion docs with new script URL (#1021)
- [x] Add "previously known as Fig" note to README.md (#1022)
- [x] Update Bash completion script
- [x] Create a `fig-stable` branch from the `1.0.0` tag
  - [x] Add a deprecation warning to all pages on http://www.fig.sh (#1025)
- [x] Create the `#docker-compose` IRC channel

After releasing on PyPi:

- [x] Add a deprecation notice to the PyPi page for `fig`

After the docs have been deployed:

- [x] Deploy http://www.fig.sh from `fig-stable`
- [x] Update README.md with new docs URL and IRC channel (#1028)

**Comment by thaJeztah** [comment]
Just to inform; upon release of compose, will there also be a `fig` alias to ease the migration? Preparing myself to make my colleagues get used to using another command (and ... tbh, `fig` is still nice and short)

Also, will `compose` still look for `fig.yml` files, or do they have to be renamed?

**Comment by dnephin** [comment]
(Linking in #864 to answer @thaJeztah question for anyone interested)

Should we close this `1.1.0` milestone and create a new `1.1.0-rc2` milestone?

**Comment by aanand** [comment]
I don't think we need to release another RC unless there are critical bugs.

**Comment by bfirsh** [comment]
I think we should release a second RC. An RC should be complete bar critical bugs. I'm not sure it needs a separate milestone though – ideally the 1.1.0 and 1.1.0-rc2 milestones should be the same. ;)

FYI – Engine and Machine are releasing second RCs on Tuesday or Wednesday.

**Comment by albers** [comment]
Will bash completion be included in the release? 
Currently bash completion is only referenced from the docs with the link pointing to the current development state in the repo. Thus, Compose and its completion are bound to run out of sync.
(This also raises the question whether putting completion on code freeze makes sense at all.)

**Comment by aanand** [comment]
The docs point to the release tag (currently `1.1.0-rc2`), so there's no risk of version drift there. I've added a checklist item to update it when we release.

**Comment by albers** [comment]
Perfect! Thanks @aanand.
